### ISSUE TITLE
html5 build, latest emscripten

### ISSUE THREAD

**Issue by unicomp21** [aerys/minko#167]
zlib.d'
lib/assimp/contrib/zlib/gzlib.c:256:24: error: implicit declaration of function
      'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        state->start = LSEEK(state->fd, 0, SEEK_CUR);
                       ^
lib/assimp/contrib/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
# define LSEEK lseek

```
            ^
```

lib/assimp/contrib/zlib/gzlib.c:256:24: note: did you mean 'fseek'?
        state->start = LSEEK(state->fd, 0, SEEK_CUR);
                       ^~~~~
                       fseek
lib/assimp/contrib/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
# define LSEEK lseek

```
            ^
```

C:\Program Files\Emscripten\emscripten\1.21.0\system\include\libc\stdio.h:71:5:
note:
      'fseek' declared here
int fseek(FILE _, long, int);
    ^
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
mingw32-make[1]: *_\* [obj/html5/release/gzlib.o] Error 1
mingw32-make: **\* [minko-plugin-assimp] Error 2
Press any key to continue . . .

**Comment by makc** [comment]
@miniduck holy crap, that was helpful. why didn't you guys submit this back to assimp?
