### ISSUE TITLE
minko assimp plugin fails to load LWO format

### ISSUE THREAD

**Issue by miniduck** [aerys/minko#168]
I cannot get lwo,lxo working with the assimp plugin in windows64 debug/release.
ascii formats like dae, obj, dxf, 3ds are working fine.

I tried building assimp non-boost standalone and it was working fine reading the files.

Tried latest minko master/dev

Breaking in Importer.cpp, SetIOHandler()

First-chance exception at 0x000007FEFD3E940D in minko-example-assimp.exe: Microsoft C++ exception: minko::file::ParserError at memory location 0x000000000022D770.
First-chance exception at 0x000000013FCCB62B in minko-example-assimp.exe: 0xC0000005: Access violation reading location 0x0000000000000020.
Unhandled exception at 0x000000013FCCB62B in minko-example-assimp.exe: 0xC0000005: Access violation reading location 0x0000000000000020.

>	minko-example-assimp.exe!std::list<std::pair<float,std::function<void __cdecl(std::shared_ptr<minko::file::AssetLibrary>,std::shared_ptr<minko::file::AbstractParser>)> >,std::allocator<std::pair<float,std::function<void __cdecl(std::shared_ptr<minko::file::AssetLibrary>,std::shared_ptr<minko::file::AbstractParser>)> > > >::size() Line 1236	C++
 	minko-example-assimp.exe!minko::Signal<std::shared_ptr<minko::file::AssetLibrary>,std::shared_ptr<minko::file::AbstractParser> >::numCallbacks() Line 117	C++
 	minko-example-assimp.exe!`minko::file::AssetLibrary::loaderCompleteHandler'::`1'::catch$0() Line 397	C++
 	[External Code]	
 	minko-example-assimp.exe!minko::file::AssetLibrary::loaderCompleteHandler(std::shared_ptr<minko::file::AbstractLoader> loader) Line 393	C++
 	[External Code]	
 	minko-example-assimp.exe!minko::Signal<std::shared_ptr<minko::file::AbstractLoader> >::execute(std::shared_ptr<minko::file::AbstractLoader> <arguments_0>) Line 164	C++
 	minko-example-assimp.exe!minko::file::FileLoader::load(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & filename, std::shared_ptr<minko::file::Options> options) Line 113	C++
 	minko-example-assimp.exe!minko::file::AssetLibrary::load(bool executeCompleteSignal) Line 348	C++
 	minko-example-assimp.exe!main(int argc, char * * argv) Line 93	C++

**Comment by promethe42** [comment]
Have you tested with the latest version on master?
