### ISSUE TITLE
Clone example does not work

### ISSUE THREAD

**Issue by mindigmarton** [aerys/minko#181]
Throws the following error:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  A label called 'run_start' already exists.
```

Happens on linux and windows. For some reason it works correctly when launched with the visual studio local debugger.

**Comment by promethe42** [comment]
Did you try with the beta2 we just pushed on master?

**Comment by mindigmarton** [comment]
Unfortunately I don't have access to linux atm, but it does work on windows now. Thanks!
