### ISSUE TITLE
Missing cef? (arch linux, 64)

### ISSUE THREAD

**Issue by josefnpat** [aerys/minko#195]
So I am `make`ing minko, and I get the following error:

    $ make config=release config=linux64_release
    [...snip...]
    Linking minko-example-html-overlay
    + g++ -o bin/linux64/release/minko-example-html-overlay obj/linux64/release/Main.o -s -m64 -L/usr/lib64 -L../../framework/bin/linux64/release -L../../plugin/html-overlay/lib/linux64 -Wl,--no-as-needed -Wl,-rpath,. -Wl,--start-group ../../framework/bin/linux64/release/libminko-framework.a ../../plugin/html-overlay/bin/linux64/release/libminko-plugin-html-overlay.a ../../plugin/sdl/bin/linux64/release/libminko-plugin-sdl.a ../../plugin/lua/bin/linux64/release/libminko-plugin-lua.a -lGL -lm -lSDL2 -lcef -Wl,--end-group
    /usr/bin/ld: cannot find -lcef
    collect2: error: ld returned 1 exit status
    Makefile:185: recipe for target 'bin/linux64/release/minko-example-html-overlay' failed
    make[1]: *** [bin/linux64/release/minko-example-html-overlay] Error 1
    Makefile:668: recipe for target 'minko-example-html-overlay' failed
    make: *** [minko-example-html-overlay] Error 2

What package am I missing, or is this an issue with the makefile?

**Comment by warrenseine** [comment]
Hi,

There's README explaining how to get it.

https://github.com/aerys/minko/blob/master/plugin/html-overlay/lib/linux64/README.txt

Regards,
Warren.

**Comment by josefnpat** [comment]
Thank you very much @warrenseine.

1) The instructions indicate that I should download 1750r1638, but I only see 1750r1805. WIll that work as well?

2) Would it make sense to either add this to the linux instructions in the README.md, or add it as a dependency to make (if that's possible?). There are quite a few dependencies that I had to meet to get as far as I did, it might be nice to list them somewhere as well.

**Comment by warrenseine** [comment]
1. Version 1750r1638 is available (just checked). I'm not sure how any other version should behave.
2. I'm surprised it's not documented. I will check and make sure it is.

**Comment by warrenseine** [comment]
Yes, found it. It's documented [here](https://github.com/aerys/minko/blob/master/doc/tutorial/Targeting_Linux.md).

**Comment by promethe42** [comment]
What dependencies did you need?

**Comment by josefnpat** [comment]
@warrenseine Thank you for your patience! I was not expecting the build docs to be in the "Targeting Linux" as I am running linux!

As for branch 1750, I do not see 1638, and none of them are marked 2014-03-13. What am I missing here?

![I don't see it!](http://i.imgur.com/7oygm8d.png)

Perhaps this would be a precursor to making an AUR for minko? Perhaps create a minko-cef, much like this: https://aur.archlinux.org/packages/desurium-cef/

**Comment by josefnpat** [comment]
@promethe42 so far I've had to `pacman -s gtk2 gtkglext`.

**Comment by promethe42** [comment]
> Thank you for your patience! I was not expecting the build docs to be in the "Targeting Linux" as I am running linux!

I'm not sure if it's sarcasm or not. Please clarify.

> so far I've had to `pacman -s gtk2 gtkglext

Those are listed in the step2 of the Targeting Linux tutorial I think:

https://github.com/aerys/minko/blob/master/doc/tutorial/Targeting_Linux.md

> As for branch 1750, I do not see 1638, and none of them are marked 2014-03-13. What am I missing here?

The "More revisions" link I guess. But that's not surprising since it's incredibly hard to spot. I miss it everytime myself.

**Comment by josefnpat** [comment]
> I'm not sure if it's sarcasm or not. Please clarify.

No sarcasm whatsoever. I do appreciate your help here. When I consider "targeting" linux, that's what I imagine I deploy to, not develop and run on. When someone says they are "targeting" linux, I imagine they are either:

a) supplying all of the dependencies that aren't common on linux as static binaries for distribution, or
b) they will be packaging it up as a deb, rpm or aur package, which will handle the dependencies themselves.

>Those are listed in the step2 of the Targeting Linux tutorial I think:

They are! Thank you! That will help me if there are any more issues beyond the CEF.

>The "More revisions" link I guess. But that's not surprising since it's incredibly hard to spot. I miss it everytime myself.

Oh my, that is *deceptive*. I didn't even realize it was a link, thank you!

**Comment by josefnpat** [comment]
So, I downloaded `cef_binary_3.1750.1638_linux64.7z`, and extracted the contents of `Release/*` into `plugin/html-overlay/lib/linux64/` as directed, now I am getting a different issue.

    ~/minko/plugin/html-overlay/lib/linux64♠ pwd
    /home/seppi/minko/plugin/html-overlay/lib/linux64
    ~/minko/plugin/html-overlay/lib/linux64♠ ls -lah
    total 481M
    drwxr-xr-x 4 seppi seppi  12K Feb  2 22:32 .
    drwxr-xr-x 8 seppi seppi 4.0K Feb  2 22:32 ..
    drwxr-xr-x 8 seppi seppi 4.0K Feb  2 22:30 cef_binary_3.1750.1638_linux64
    -rw-r----- 1 seppi seppi 380M Feb  2 22:28 cef_binary_3.1750.1638_linux64.7z
    -rwxr-xr-x 1 seppi seppi  24K Mar 13  2014 chrome-sandbox
    -rwxr-xr-x 1 seppi seppi 101M Mar 13  2014 libcef.so
    -rwxr-xr-x 1 seppi seppi 1.3M Mar 13  2014 libffmpegsumo.so
    -rw-r--r-- 1 seppi seppi  252 Feb  1 20:43 README.txt
    drwxr-xr-x 2 seppi seppi 4.0K Feb  2 22:32 Release



    $ make config=release config=linux64_release verbose=1

[snip]

    test -e /home/seppi/minko/framework/asset && cp -R /home/seppi/minko/framework/asset "bin/linux64/release" || :
    test -e asset && cp -R asset "bin/linux64/release" || :
    test -e /home/seppi/minko/plugin/lua/asset && cp -R /home/seppi/minko/plugin/lua/asset "bin/linux64/release" || :
    test -e /home/seppi/minko/plugin/html-overlay/asset && cp -R /home/seppi/minko/plugin/html-overlay/asset "bin/linux64/release" || :
    test -e /home/seppi/minko/plugin/html-overlay/lib/resource/locales && cp -R /home/seppi/minko/plugin/html-overlay/lib/resource/locales "bin/linux64/release" || :
    test -e /home/seppi/minko/plugin/html-overlay/lib/resource/cef.pak && cp -R /home/seppi/minko/plugin/html-overlay/lib/resource/cef.pak "bin/linux64/release" || :
    test -e /home/seppi/minko/plugin/html-overlay/lib/resource/devtools_resources.pak && cp -R /home/seppi/minko/plugin/html-overlay/lib/resource/devtools_resources.pak "bin/linux64/release" || :
    test -e /home/seppi/minko/plugin/html-overlay/lib/linux64/libcef.so && cp -R /home/seppi/minko/plugin/html-overlay/lib/linux64/libcef.so "bin/linux64/release" || :
    test -e /home/seppi/minko/plugin/html-overlay/lib/linux64/libffmpegsumo.so && cp -R /home/seppi/minko/plugin/html-overlay/lib/linux64/libffmpegsumo.so "bin/linux64/release" || :
    test -e /home/seppi/minko/plugin/html-overlay/lib/linux64/chrome-sandbox && cp -R /home/seppi/minko/plugin/html-overlay/lib/linux64/chrome-sandbox "bin/linux64/release" || :
    Linking minko-example-html-overlay
    /home/seppi/minko/tool/lin/script/g++.sh g++ -o bin/linux64/release/minko-example-html-overlay obj/linux64/release/Main.o     -s -m64 -L/usr/lib64 -L../../framework/bin/linux64/release -L../../plugin/html-overlay/lib/linux64 -Wl,--no-as-needed -Wl,-rpath,. ../../framework/bin/linux64/release/libminko-framework.a ../../plugin/html-overlay/bin/linux64/release/libminko-plugin-html-overlay.a ../../plugin/sdl/bin/linux64/release/libminko-plugin-sdl.a ../../plugin/lua/bin/linux64/release/libminko-plugin-lua.a -lGL -lm -lSDL2 -lcef
    + g++ -o bin/linux64/release/minko-example-html-overlay obj/linux64/release/Main.o -s -m64 -L/usr/lib64 -L../../framework/bin/linux64/release -L../../plugin/html-overlay/lib/linux64 -Wl,--no-as-needed -Wl,-rpath,. -Wl,--start-group ../../framework/bin/linux64/release/libminko-framework.a ../../plugin/html-overlay/bin/linux64/release/libminko-plugin-html-overlay.a ../../plugin/sdl/bin/linux64/release/libminko-plugin-sdl.a ../../plugin/lua/bin/linux64/release/libminko-plugin-lua.a -lGL -lm -lSDL2 -lcef -Wl,--end-group
    /usr/bin/ld: warning: libgcrypt.so.11, needed by ../../plugin/html-overlay/lib/linux64/libcef.so, not found (try using -rpath or -rpath-link)
    /usr/bin/ld: warning: libudev.so.0, needed by ../../plugin/html-overlay/lib/linux64/libcef.so, not found (try using -rpath or -rpath-link)
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_monitor_unref'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_enumerate_scan_devices'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_new'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_list_entry_get_name'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_enumerate_get_list_entry'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `gcry_control@GCRYPT_1.2'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_list_entry_get_next'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_device_new_from_syspath'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_monitor_receive_device'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_device_get_property_value'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_unref'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_monitor_enable_receiving'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_monitor_filter_add_match_subsystem_devtype'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_monitor_get_fd'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_device_get_devnode'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_device_get_subsystem'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_enumerate_unref'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_enumerate_new'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_device_get_parent_with_subsystem_devtype'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_monitor_new_from_netlink'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_device_unref'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_device_get_sysattr_value'
    ../../plugin/html-overlay/lib/linux64/libcef.so: undefined reference to `udev_enumerate_add_match_subsystem'
    collect2: error: ld returned 1 exit status
    Makefile:185: recipe for target 'bin/linux64/release/minko-example-html-overlay' failed
    make[1]: *** [bin/linux64/release/minko-example-html-overlay] Error 1
    Makefile:668: recipe for target 'minko-example-html-overlay' failed
    make: *** [minko-example-html-overlay] Error 2

**Comment by promethe42** [comment]
Please open another issue for this. And don't forget to provide this trace.
