### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by AbdealiJK** [aerys/minko#196]
I want to make a game with bluetooth communication for Android and came across minko.

I noticed it was written in C++ ... So, I guess I cannot write Native Java bluetooth communication.

So, Is there a way to send data with bluetooth ?

**Comment by promethe42** [comment]
`So, I guess I cannot write Native Java bluetooth communication.`

Why not?
The html-overlay plugin uses a Java/C++ bridge using the JNI API to do exactly that.

`So, Is there a way to send data with bluetooth ?`

http://stackoverflow.com/questions/21207047/android-bluetooth-library-porting-to-jni

**Comment by AbdealiJK** [comment]
I see, thanks
