### ISSUE TITLE
Emscripten TOTAL_MEMORY doesn't get picked up

### ISSUE THREAD

**Issue by fjallraven** [aerys/minko#201]
Running master + emscripten 1.29.0 + Windows

This can be tested by replacing the geo in assimp example with a huge geometry file. (and removing the animation calls..... ;))
Error:
```
Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 134217728, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
```

So I updated the emcc postbuild with -s TOTAL_MEMORY=536870912. Clean, build, but getting exactly the same error no matter what. (value always repeated)

Any ideas?

Thank you!

**Comment by warrenseine** [comment]
If you build with `make config=html5_release verbose=1`, do you see your change in the command line?

Make sure you regenerate the solution when you change a command line parameter.

Note that the new recommended way to manage memory limits is ALLOW_MEMORY_GROWTH. This will be enabled by default in Emscripten in a few days.

**Comment by promethe42** [comment]
TOTAL_MEMORY is set in the HTML template. If you to customize it, edit the value is the JS code of the template.html file in the root dir of your app.

**Comment by fjallraven** [comment]
Ah thanks guys, the emcc was printing out the correct value passed in so was a bit confused.

So memory growth wont cause much slow down? So it should be safe to use incoming with minko?

**Comment by promethe42** [comment]
> So memory growth wont cause much slow down? So it should be safe to use incoming with minko?

In our experience memory growth is fine. We will actually use it in production.

The next version of the engine will also come with a much (much!) lower memory footprint.
