### ISSUE TITLE
std::shared_ptr<T>(new T(...)) instead of std::make_shared<T>(...)

### ISSUE THREAD

**Issue by tforgione** [aerys/minko#205]
Hi everyone,

I was browsing the source code of this repository, and I was wondering if there was a specific reason for using 

``` cpp
auto ptr = std::shared_ptr<T>(new T(...));
```

instead of 

``` cpp
auto ptr = std::make_shared<T>(...);
```

[CppReference](http://en.cppreference.com/w/cpp/memory/shared_ptr#Notes) says that the second one is faster since it makes only one memory allocation (for the ref counter) but the first version makes one allocation during the `new` creating the `T` and another one in the constructor of `std::shared_ptr` to allocate the ref count.

Thanks in advance.

**Comment by promethe42** [comment]
make_shared require ctors to be public.

**Comment by tforgione** [comment]
Fair enough, thanks for answering so fast, and sorry for the inconveniance

**Comment by promethe42** [comment]
Note that for the dev branch, the use of shared_ptr has been limited a lot.

There are ways to allow the use of make_shared with private ctors. We might use them in the near future.
