### ISSUE TITLE
Main website's been "cybersquatted".

### ISSUE THREAD

**Issue by KarjamP** [aerys/minko#206]
If you don't know what Cybersquatting is, according to Wikipedia, it is "registering, trafficking in, or using an Internet domain name with bad faith intent to profit from the goodwill of a trademark belonging to someone else."

In this case, http://minko.io/ had apparently been stolen from you guys and turned into a website promoting a freemium cloud-based 3D model viewer. Proof can be seen by clicking on either the links "Official website" or the link "Forums" on the "readme.md" Github page.

In the case of the former link, it describes a product totally different from this one. In the case of the latter, it leads to a 404 link.

**Comment by promethe42** [comment]
Cybersquatting with the same logo, the same company with the same address and even the same pages (http://minko.io/engine/) properly referencing the same developer tools and the same documentation?

Hmmmm... that's not cybersquatting. It's called an update.

Thanks for the heads up anyway :)

**Comment by KarjamP** [comment]
While I'm not afraid to admit mistakes, you should probably update the now outdated links within the readme.md file to point to the new links.

**Comment by promethe42** [comment]
The "Official website" link validity is debatable. Minko is the name of both the cloud platform and the developer tools. We might redirect to /engine instead.

The "Forums" link is plain wrong and should redirect to stackoverflow instead.

Just logged #207

**Comment by promethe42** [comment]
I shall give you a cookie. But I don't have cookies on my repo. So here is a badass dragon instead :)

http://minko.io/app/#/link/d8da97a7f4
