### ISSUE TITLE
keyboard inputs don't work in html-overlay + linux

### ISSUE THREAD

**Issue by bgbnbigben** [aerys/minko#208]
Using an <input> field inside the html-overlay plugin doesn't seem to accept input. On my linux64 machine each keystroke triggers an error similar to the following:

`[0402/112706:ERROR:browser_main_loop.cc(234)] Gdk: IA__gdk_keymap_get_entries_for_keyval: assertion 'keyval != 0' failed`

I haven't tested this on android nor iphone yet but I suspect this issue likely occurs on those platforms too.

**Comment by warrenseine** [comment]
The error you've got looks related to your installed GTK version, which might be incompatible with the CEF framework we use.

* Does this happen with other HTML elements?
* Did you install the supported libraries as [documented](https://github.com/aerys/minko/blob/master/doc/tutorial/Targeting_Linux.md)?
* What's your operating system?

> I haven't tested this on android nor iphone yet but I suspect this issue likely occurs on those platforms too.

I wouldn't expect that. On mobile platforms, we're using a completely different technology to render HTML content (webview vs. embedded browser).

**Comment by bgbnbigben** [comment]
It happens with both `<input>` and `<textarea>`, whether or not they're subelements of a `<form>` or not.
I have both `libgtk2.0-dev` and `libgtkglext1-dev` installed on Ubuntu 14.04 -- though it's running under a virtualbox, which might be an issue. I also have cef_binary_3.1750.1638_linux64 installed as per the instructions in the README.

There are also two start-up log messages that I hadn't noticed but don't *believe* are part of the problem:

    [0403/081811:ERROR:proxy_service_factory.cc(103)] Cannot use V8 proxy resolver in single process mode
    [0403/081811:WARNING:proxy_service.cc(890)] PAC support disabled because there is no system implementation

**Comment by promethe42** [comment]
I confirm the bug does exist on Linux.

@bgbnbigben did you find a solution?

**Comment by promethe42** [comment]
Hello,

the fix is rather simple: we have to fill the CefKeyEvent::native_key_code and CefKeyEvent::unmodified_character properties like this:

```
keyEvent.windows_key_code = key;
keyEvent.native_key_code = key;
keyEvent.unmodified_character = key;
```

You have to do this in all keyboard callbacks (key down, key up, text input) in ChromiumApp.cpp. The fix will soon be on the dev branch.

**Comment by bgbnbigben** [comment]
Hi there,

No, I didn't find a solution -- it didn't particularly bother me since Warren suggested it was a different technology to mobile (and I'm only required to target mobile for this project, though perhaps in the future we might also move to desktop). However, it seems you found a fix; great news! I currently only have an android build on hand so can't test this on linux, but shall clone the dev branch in a few days to confirm.

**Comment by bgbnbigben** [comment]
I don't believe this is a complete fix; for instance, the backspace button doesn't register with this fix.

**Comment by promethe42** [comment]
Correct. Some specific keys still don't work. Yet they work just fine on
Windows. This is still likely a Linux specific issue.
