### ISSUE TITLE
Mistaken skeleton solution path in dev branch

### ISSUE THREAD

**Issue by tul1** [aerys/minko#217]
At least solution_gmake_gcc.sh and solution_gmake_clang.sh in the dev branch in the skeleton file have wrong path to premake5.lua. Should be ${MINKO_HOME}/script/ instead of ${MINKO_HOME}/tool/lin/script/ .

**Comment by Ithamar** [comment]
yes, I noticed this too, and it is not just skeleton that's broken, although it is the most obvious (and painful, as it is supposed to be the template you start new projects from). @tul1 , if you don't get around to it, I might post a pull to fix this...
