### ISSUE TITLE
Can I set the mouse cursor position?

### ISSUE THREAD

**Issue by Miguel2706** [aerys/minko#219]
Hello, I'm creating a First person video game and I need to move the mouse to the center of the window, I know that I can move it with SDL (SDL_WarpMouseInWindow), but I don't how to do it with minko. So Can I move the mouse? Sorry for my bad english

**Comment by warrenseine** [comment]
Minko uses SDL to setup the window and the context. Therefore, you can use SDL functions directly in your C++ code.

Depending on your target platform, it might be a little harder. For instance, in HTML5, the mouse is managed by the browser and SDL functions are just wrappers around browser APIs. I don't know if the SDL functions to control the mouse have been correctly implemented in Emscripten. You'll have to test.

**Comment by Miguel2706** [comment]
Ok, thanks! :)
