### ISSUE TITLE
Any plans for updating the tutorials / examples in dev branch?

### ISSUE THREAD

**Issue by Ithamar** [aerys/minko#222]
Most of the tutorials and examples in the dev branch are broken due to the Matrix4x4 => mat4 and Vector3 => vec3 changes. I really miss them, and they are not always as obvious to fix.

Is there anyone already working on that, or is it worth sending some pulls to fix (at least some of) them?

**Comment by promethe42** [comment]
Yes a new member of the team made a complete list of the things to fix. It should be fixed next month.

**Comment by Ithamar** [comment]
ah ok, cool, so I'll let him do it then...
