### ISSUE TITLE
HTML5 cannot find path

### ISSUE THREAD

**Issue by renindustries** [aerys/minko#228]
I followed the exact instructions found at [Compiling SDK for HTML5](https://github.com/aerys/minko/blob/master/doc/tutorial/Compiling_the_SDK_for_HTML5.md), but ran afoul the following error:

![2015-10-23 20_18_12-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/7120679/10707648/97b1e6f6-79c3-11e5-91e5-a2e20c68f641.png)

**Comment by renindustries** [comment]
I should mention, this is an entirely new application. I just copied the skeleton and renamed it.

**Comment by warrenseine** [comment]
The `%MINKO_HOME%` token should have been replaced by the actual path. Can you make sure you have defined the environment variable?

**Comment by renindustries** [comment]
![2015-10-24 10_20_01-environment variables](https://cloud.githubusercontent.com/assets/7120679/10710887/d3fd9626-7a38-11e5-82fa-c3b61168fbac.png)

It's well defined, and I can compile Minko normally, so it seems to be working.

**Comment by warrenseine** [comment]
Hum, maybe there's an issue on the master branch. Can you try dev?

**Comment by renindustries** [comment]
Sure, let me pull it and do a recompile.

**Comment by renindustries** [comment]
@warrenseine So, I pulled dev branch and tried to run build_html5.bat, and it didn't work.

However, I also noticed that the dev branch has no tool folder. Which build_html5.bat requires.

![2015-10-24 14_08_34-aerys_minko at dev](https://cloud.githubusercontent.com/assets/7120679/10711927/ca29f2e6-7a58-11e5-9081-11678c506096.png)

So it couldn't work, even in theory.

**Comment by renindustries** [comment]
@warrenseine If I force it to use premake5 by making the folder or pointing it to bin/windows32/, I can get HTML5 to at least compile, but it seems unable to link or find libraries:

![2015-10-24 14_16_22-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/7120679/10711975/e7732aec-7a59-11e5-8bad-634256c4e8bd.png)

With several pages of complaints about unresolved symbols.

**Comment by renindustries** [comment]
Even cut down to just SDL, it fails. Cutting out SDL, it still can't find the minko-framework. Not sure why.

**Comment by warrenseine** [comment]
I just tested and it runs fine on the dev branch when running `solution_gmake_min.bat` then `build_html5_release.bat`. What errors do you get?

**Comment by renindustries** [comment]
I'm getting compiler errors during `build_html5_release.bat`:

![2015-10-24 15_06_02-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/7120679/10712190/0574afa0-7a61-11e5-9d97-816e3b841dcc.png)

**Comment by warrenseine** [comment]
I've no idea what's going on (first time I see this error). Anyway, Emscripten 1.25 is quite old. We're compiling with Emscripten 1.29 at least. The most recent is 1.34.1 in the SDK. Can you upgrade?

**Comment by renindustries** [comment]
@warrenseine Absolutely! The documentation said 1.25, so I tested on latest and that version, thus the outdated version. Should I upgrade to 1.34.1?

**Comment by warrenseine** [comment]
This documentation needs a major cleanup. Yes, you should.

**Comment by renindustries** [comment]
Update: I can confirm that mainline, out of the box, with your instructions, is capable of working with 1.25. Dev channel does not work, going to try upgrading emscripten to newest.

**Comment by renindustries** [comment]
After very carefully upgrading and a lot of retries, I can now use 1.29 to consistently build mainline.

Dev channel fails on SDL_Audio, and I can't seem to get past it:

![2015-10-24 22_31_52-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/7120679/10713770/3b087302-7a9f-11e5-8f61-c37f1ee8f25e.png)

I'll repeat on higher versions of emscripten.

**Comment by renindustries** [comment]
1.30 had clang/LLVM just straight up crash, 1.34 had SDL_Audio problems. Guess I'm stuck with 1.29 on mainline.

![2015-10-24 23_08_29-glossary of numismatics - wikipedia the free encyclopedia - opera](https://cloud.githubusercontent.com/assets/7120679/10714098/4f303a28-7ab2-11e5-913f-758a6456a41e.png)

**Comment by warrenseine** [comment]
I've just pushed a ton of changed to dev. May be worth a retry.

**Comment by renindustries** [comment]
@warrenseine Yeah! It compiles now on 1.29. However, `skeleton/build_html5.bat` does not, and cannot, work; it points to %MINKO_HOME%/tools, which no longer exists. I tried to point it towards `%MINKO_HOME%/script/premake.bat`, but I couldn't get it to work. Perhaps you could point it towards `%MINKO_HOME%/bin/windows32/premake.exe`?

**Comment by renindustries** [comment]
@warrenseine Dev channel compiles but won't render anything.

**Comment by promethe42** [comment]
@renindustries open a new issue about that please
