### ISSUE TITLE
missing pthread param on Makefiles

### ISSUE THREAD

**Issue by gerardogc2378** [aerys/minko#230]
Over ArchLinux (64 bits) I have this output compiling 01-hello-cube example

Running pre-link commands
test -e /home/ggc/tmp/minko/framework/asset && cp -R /home/ggc/tmp/minko/framework/asset "bin/linux64/release" || :
test -e asset && cp -R asset "bin/linux64/release" || :
Linking minko-tutorial-01-hello-cube
+ g++ -o bin/linux64/release/minko-tutorial-01-hello-cube obj/linux64/release/main.o -s -m64 -L/usr/lib64 -L../../framework/bin/linux64/release -Wl,--no-as-needed -Wl,--start-group ../../framework/bin/linux64/release/libminko-framework.a ../../plugin/sdl/bin/linux64/release/libminko-plugin-sdl.a -lGL -lm -lSDL2 -Wl,--end-group
/usr/bin/ld: ../../framework/bin/linux64/release/libminko-framework.a(Worker.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:223: recipe for target 'bin/linux64/release/minko-tutorial-01-hello-cube' failed
make: *** [bin/linux64/release/minko-tutorial-01-hello-cube] Error 1

To fix

Add pthread parameter into your Makefile in question
 
ALL_LDFLAGS += $(LDFLAGS) -s -m64 -L/usr/lib64 -L../../framework/bin/linux64/release -Wl,--no-as-needed -lpthread

And compile again, enjoy your cube ... :D

How to fix this automatically?

**Comment by promethe42** [comment]
Which branch ?

**Comment by gerardogc2378** [comment]
master branch

**Comment by promethe42** [comment]
Please try the dev branch and confirm it works.

**Comment by warrenseine** [comment]
@gerardogc2378 Did you try to build `dev`?

**Comment by gerardogc2378** [comment]
Today I'll try with dev branch at tonight ...

**Comment by gerardogc2378** [comment]
Playing with dev branch on minko/tutorial all examples are missing -lpthread flag, except on android targets

**Comment by warrenseine** [comment]
That shouldn't be the case. Look (here)[https://github.com/aerys/minko/blob/dev/module/minko/minko.project.lua#L128].

**Comment by promethe42** [comment]
@gerardogc2378 have you re-generated the whole solution, even for examples, after switching to dev? To be sure, delete all the Makefile files then re-generate the solution.
