### ISSUE TITLE
Build issue for Debian 8 (Jessie) plus workaround

### ISSUE THREAD

**Issue by jjoganic** [aerys/minko#231]
The premake executable appears to contain a hard-coded library path of -L/usr/lib64.  This directory does not exist on Debian 8.  As a result, the libGL.so fails to link when compiling the examples.

Setting LDFLAGS prior to building the SDK seems to take care of that.

`$ export LDFLAGS="-L/usr/lib/x86_64-linux-gnu -lpthread"`

I did not have any difficulty building or running the minko-example-cube executable after that.

Ideally, it should be possible to recompile the premake executable, but I'm not finding the source code in the tree.  Perhaps someone can provide the location.  I can understand using an ELF binary to generate the Makefiles, but from a bootstrapping point of view, perhaps compiling it from source prior to using it would obviate the need to commit opaque, monolithic executables directly into the repo.

**Comment by promethe42** [comment]
Thanks for the feedback.

Wouldn't it be simpler to add the Debian-specific missing `-L` and let the hard-coded `-L/usr/lib64` to be ignored?

**Comment by warrenseine** [comment]
Thanks for the workaround.

The bundled premake executable is a custom-built premake5 from a year ago. We'll definitely switch to a more recent one (hopefully when premake5 is out). In the meantime, we'll stick to a workaround.

The fix @promethe42 suggests should be implemented in `module\minko\minko.project.lua`. PR welcome if you want to contribute.
