### ISSUE TITLE
minko gestures

### ISSUE THREAD

**Issue by gerardogc2378** [aerys/minko#232]
Hi to everyone, I have one question, like title any sample with gestures?

**Comment by promethe42** [comment]
What kind of gestures are you referring to?

**Comment by gerardogc2378** [comment]
Like this https://en.m.wikipedia.org/wiki/Pointing_device_gesture

**Comment by warrenseine** [comment]
No, sorry, we don't have any example for this kind of use.

You should be able to look at the examples that use the mouse and be able to implement it yourself using mouse coordinates.
