### ISSUE TITLE
What about Font with TTF

### ISSUE THREAD

**Issue by gerardogc2378** [aerys/minko#233]
Is there example or tutorial for ttf-font and text to show on screen?

**Comment by promethe42** [comment]
If you are trying to build a UI I would recommend you to have a look at the HTML overlay plugin. It makes it easy to build complex cross platform responsive UIs using HTML5 and CSS3, including using TTF fonts and many other things. Here is an example: https://github.com/aerys/minko/tree/dev/example/html-overlay

You should also be able to use TTF fonts through SDL. But we have no example for this and I don't know how portable it is.

**Comment by gerardogc2378** [comment]
Thanks, I saw your example by this comment, really NICE HTML overlay :D, thanks again
