### ISSUE TITLE
link OBJ models to HTML5 DOM element?

### ISSUE THREAD

**Issue by jeffrey-effendy** [aerys/minko#234]
Is it possible to upload .obj files at runtime and link models to HTML5 DOM element?

**Comment by promethe42** [comment]
What do you mean by

> link models to HTML5 DOM element?

**Comment by jeffrey-effendy** [comment]
what i mean is that, let s say, I have HTML5 input tag that browses and upload an OBJ file. For this, is it possible to update the OBJ file on runtime, such that whenever I upload and replace the previous OBJ file, it gets updated?

**Comment by warrenseine** [comment]
Ok, then yes, but this is not specific to Minko.

When a file is uploaded, you should [call a C function from JavaScript](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html) that will tell your application to download the new model, add it to the scene, and remove the previous one.

**Comment by warrenseine** [comment]
Would that work for you?

**Comment by jeffrey-effendy** [comment]
yup, able to do it, thanks a lot!
