### ISSUE TITLE
Building the SDK and Creating a new app 

### ISSUE THREAD

**Issue by unco182** [aerys/minko#240]
Hi, 

I have some trouble to succeed in creating a Minko Hello World project.
First while building the SDK on OSX I wasn't able to find tool/mac/script/solution_xcode.sh, finally I found an other way to build it (by finding the .sh that was moved). 

Now I'm stuck after copying MINKO_HOME/skeleton and renaming it because the solution_xcode.sh to create the workspace was also moved so script/solution_xcode.sh is not working. I tried editing this script to target a good directory but I didn't succeed in it. 

Do you have any tip, advice to help ?

Thx in advance

**Comment by warrenseine** [comment]
We are in the process of fixing the documentation which has been outdated for too long. Thanks for reporting this, we'll make sure it's fixed.

First, can you make sure you are using the `dev` branch? I've recently tested the `script/solution_xcode_osx.sh` and `script/solution_xcode_ios.sh` scripts and they work fine with Xcode 7.

**Comment by unco182** [comment]
Thanks for your quick answer, In the end I succeed in building the Xcode project by changing path in solution_xcode_ios.sh to target the good directory
