### ISSUE TITLE
Compiling the Android SDK Tutorial, is outdated

### ISSUE THREAD

**Issue by JinnZ** [aerys/minko#243]
Hi guys,
By trying to fullfill the tutorial on Windows, i can report you that:
  At Step 2 :
    _Run the following script:
    Windows and Linux: tool/lin/script/install_jni.sh_
    Please precise it must be found in the minko directory, plus that it's now in minko/script/install_jni.sh and that Cygwin is required here fore Windows (Obvious for experimented Linux user but not necessary for the rest of the world)
    I can also add that the script require minor correction at line 71 and 75 :
    71 : if [[ ! -x ${ANDROID_HOME}/ndk/build/tools/make-standalone-toolchain.sh ]]; then
    75 : ${ANDROID_HOME}/ndk/build/tools/make-standalone-toolchain.sh --system=${ANDROID_SYSTEM} --platform=${ANDROID_SDK_VERSION} --toolchain=${ANDROID_TOOLCHAIN} --install-dir=${ANDROID_NDK_HOME}
    Otherwise the script could only work by starting it by being in the pwd=ndk...
   At Step 3 :
     tool/lin/script/solution_gmake_android.sh          doesn't exist anymore
     I'm expecting it's minko/script/solution_gmake_full.sh now (in Cygwin)

    I'm just starting Step 4 so i will try to complete this ticket later.
Thx and Good luck

**Comment by warrenseine** [comment]
Thank you for your feedback. The documentation will be updated.
