### ISSUE TITLE
Linking iOS objective C Project with Minko C++ 

### ISSUE THREAD

**Issue by unco182** [aerys/minko#244]
Hi, 

I would like to know the best way to develop an iOS app with minko SDK.

Should I start from the XCode project generated by minko script ? If yes how can I add a ViewController to be able to move in my 3D scene ?

OR

Should I start with a fresh XCode Objective C project and link it to Minko SDK ? In that case, how do you link the project to the SDK to have all the include integrated in the project?

I tried the second option for now but when building I got an error because the project is not able ton find minko/Minko.hpp file

Thanks in advance!

**Comment by Noxalus** [comment]
You should choose the first solution instead. However, the ViewController is created by SDL ([here](https://github.com/aerys/minko/blob/master/plugin/sdl/lib/sdl/src/video/uikit/SDL_uikitwindow.m#L119)), you don't need to create another one to move in your 3D scene.

**Comment by unco182** [comment]
Ok thanks, 

But should I enable something in minko SDK to be able to move in my scene? cuz for now I'm displaying the scene but I'm not able to move in it

**Comment by Noxalus** [comment]
No, there is nothing to enable, It's up to you to write the code to move the camera like you want. Look at the [serializer example](https://github.com/aerys/minko/blob/master/example/serializer/src/main.cpp#L100), there is some code to move the camera around the world origin with the mouse.

**Comment by unco182** [comment]
Thanks so much again !
