### ISSUE TITLE
Getting bounds of 3D model 

### ISSUE THREAD

**Issue by unco182** [aerys/minko#245]
Hi,

I would like to put the center of the 3D universe of my app in the center of my 3D model and make the camera look at it.
I thought that using canvas->width() and canvas->height() would help me to get to the center. But the size of my canvas is (640,920). 
How can I get the max size of my 3D model instead?

Thx in advance

**Comment by warrenseine** [comment]
You should add a [`BoundingBox`](https://github.com/aerys/minko/blob/bd9a1672e29eb8e5ef874a1670d10949e8ed171f/framework/include/minko/component/BoundingBox.hpp) component to your model node and get its `box()` property.

**Comment by unco182** [comment]
Thanks ! 

Is there any up to date example that use BoudingBox ?

**Comment by promethe42** [comment]
```cpp
auto bbox = component::BoundingBox::create();
node->addComponent(bbox);
```

Then you have the `bbox->box()->width(), `height`and `depth` properties.
