### ISSUE TITLE
Integration with OpenFramework / Flatbuffers / Nanomsg

### ISSUE THREAD

**Issue by lucmichalski** [aerys/minko#247]
Hi guys,

Hope you are doing all well!

I was checking out your great framework in order to know if u have ever considered to create a bridge with your engine and the [Open Frameworks](https://github.com/openframeworks/openFrameworks) project.

Also, have u ever considered to use [Google Flatbuffers](https://github.com/google/flatbuffers) or [nanomsg](http://nanomsg.org/) (like to distribute tasks or requests to sub services (remote queries or local bindings) with the surveyor pattern for eg.) in order to improve the overall performances on a mobile devices also?

I would be really curious to read your input about these features.

Cheers,
Luc Michalski

**Comment by warrenseine** [comment]
Hi,

We have no plan to integrate with Open Frameworks. I do think it'd be quite easy though as they're both open cross-platform C++ code.

We came across Flatbuffers a few months ago and I think it's a great project. We do not have use for it as our file format is based on [MessagePack](https://github.com/msgpack/msgpack-c) at the moment. I wonder how big that could improve performances. Maybe in a future version!

nanomsg, on the other hand, sounds like a very specific use case. I would not see this as a public Minko plugin. A generic socket library would be more useful for anybody who wants to integrate a communication layer in Minko.

Cheers,
Warren.

**Comment by promethe42** [comment]
I would love to see a refactor of the "serializer" plugin using Flatbuffers instead of MessagePack. I guess it would come with great performance improvements, especially for streaming since Flabuffers is lighter and could be easier to parallelize.
