### ISSUE TITLE
where is minko shaderlab and shaderStudio

### ISSUE THREAD

**Issue by laishi** [aerys/minko#249]
where is minko shaderlab and minkostudio ,this two and minko relationship？
shaderlab https://www.youtube.com/watch?v=yuR1e1PjU8Y
minkostudio https://www.youtube.com/watch?v=fczDdeMG860
others
I use fedora 23 , i use git clone https://github.com/aerys/minko.git ,can not compiler and use minko
minko look very powerful，I want use it , but Too difficult，hope some video tutorial.
thanks++

**Comment by promethe42** [comment]
Hello,

Minko ShaderLab and Minko Studio were meant for the previous version of Minko and were built with ActionScript 3. Mink Studio will likely be replaced by the Blender plugin we're working on (see #220).

> I [...] use fedora 23can not compiler and use minko

We use Ubuntu and we never tested it with fedora 23 but it should work.
Just follow the [Targeting Linux](https://github.com/aerys/minko/blob/master/doc/tutorial/Targeting_Linux.md) documentation and tell us what doesn't work.

**Comment by warrenseine** [comment]
@laishi Can you create a separate issue with more details for the Fedora problem?

**Comment by laishi** [comment]
1).Installing the SDK sources

my working dir is:/home/laishi/Work/Web/WebGL

git clone https://github.com/aerys/minko.git

2).set environment variable:

echo "export MINKO_HOME=/home/laishi/Work/Web/WebGL/minko/sdk">> ~/.bashrc

3).Installing toolsets (Compiling the SDK for Linux)
	gcc -v
	gcc (GCC) 5.3.1 20151207 (Red Hat 5.3.1-2)

	in fedora 23 Install libraries

	No package software-properties-common available.

	No package libgl1-mesa-dev available.
	No package libglu1-mesa-dev available.
	No package libglew-dev available.
	No package libsdl2-dev available.
	No package libcurl4-openssl-dev available.
	No package libudev-dev available.
	No package libxinerama-dev available.
	No package libgtk2.0-dev available.

	so i skip them


	Generate the solution
	cd script/

	./solution_gmake_gcc.sh
	error:
	bash: ./solution_gmake_gcc.sh: No such file or directory
	here is script dir files

	build_android_debug.bat    build_html5_debug.sh     fail.bat                premake5.sh               solution_vs2013_min.bat
	build_android_debug.sh     build_html5_release.bat  fail.sh                 solution_gmake_full.bat   solution_vs2015_full.bat
	build_android_release.bat  build_html5_release.sh   install_emscripten.bat  solution_gmake_full.sh    solution_vs2015_min.bat
	build_android_release.sh   clean.bat                install_emscripten.sh   solution_gmake_min.bat    solution_xcode_ios.sh
	build_android.sh           clean.sh                 install_jni.sh          solution_gmake_min.sh     solution_xcode_osx.sh
	build_html5_debug.bat      cpjf.sh                  premake5.bat            solution_vs2013_full.bat


	then use:
	./solution_gmake_full.sh
	show this
	You must define the environment variable EMSCRIPTEN to be able to target HTML5.
	You must define the environment variable ANDROID_HOME to be able to target Android.
	Building configurations...
	Running action 'gmake'...
	Building configurations...
	Running action 'gmake'...
	Generating Makefile...	
	.....
	Done.



	then: to ../skeleton/script/

4).Build the solution
make config=linux64_release;
make: *** No targets specified and no makefile found.  Stop.

**Comment by laishi** [comment]
@Jean-Marc Le Roux
3. Mink Studio will likely be replaced by the Blender plugin we're working on (see #220).

where is the blender plugin download

thanks a lot

**Comment by warrenseine** [comment]
@laishi Please create a separate issue for your compilation problem.
