### ISSUE TITLE
Collision detection 

### ISSUE THREAD

**Issue by gerardogc2378** [aerys/minko#251]
Is there a sample about collision detection?

**Comment by warrenseine** [comment]
[Yes](https://github.com/aerys/minko/tree/master/example/physics)

**Comment by warrenseine** [comment]
Maybe I was a bit fast. Do you mean a callback when a collision occurs?

**Comment by gerardogc2378** [comment]
Exactly...

**Comment by promethe42** [comment]
Just listen to the `bullet::Collider::collisionStarted` signal.

**Comment by gerardogc2378** [comment]
Thanks
