### ISSUE TITLE
Integration with UIKit

### ISSUE THREAD

**Issue by che1404** [aerys/minko#259]
Hi all, and thanks for the Minko framework!
I've installed the SDK and launched my first app in the iPad simulator. Looks promising!

I'm wondering if there is a way to integrate a Minko scene inside a UIView, so I can make it part of a native UIKit application (i.e only appears when the user selects a specific tab item).

Thanks!
Robert.

**Comment by promethe42** [comment]
I guess you'd have to play with the context/window init in the SDL2 plugin to attach it to a custom UIView.

If you want your UI to be x-platform, you should have a look at the HTML overlay plugin to build your UI in HTML5.
