### ISSUE TITLE
Has minko been abandaned by original developers?

### ISSUE THREAD

**Issue by zwcloud** [aerys/minko#264]
Has minko been abandaned by original developers? The latest commit is [a382559](https://github.com/aerys/minko/commits/dev)  on 24 Feb 2017.

**Comment by promethe42** [comment]
No. We will push some updates soon, mainly adding a CMake based build system and a WASM target.
But the engine is "bug free" and we're using it to build our projects.

**Comment by Borderliner** [comment]
Is your GitLab instance a private repo?

**Comment by promethe42** [comment]
Yes.

**Comment by Borderliner** [comment]
No progress yet?

**Comment by underdoeg** [comment]
also wondering about the cmake build system?

**Comment by Borderliner** [comment]
Please make this piece of software public.

**Comment by promethe42** [comment]
Hello,

Sorry for the wait! 
We've re-enabled the git repo sync.

The repo should now be up to date automatically.
