### ISSUE TITLE
Integration into Qt

### ISSUE THREAD

**Issue by thinkgamesdeveloper** [aerys/minko#268]
Hi,
First I would like to thank you for this amazing work.

I am trying to use minko into a project with Qt. I am asking if you had already try to integrate 3D scene from minko into Qt, specially into a Qml item. Or if you have an idea how I do do that.

Thank you in advance for your help. 

Regrads.

**Comment by JMLX42** [comment]
Hi, 

No we never worked on any project using Qt. I'll be happy to get any feedback from you on this.

**Comment by thinkgamesdeveloper** [comment]
Hi, 
ok thank you for your response
I will try to make it work with Qt and I will give you a feedback.
